# Generated by Django 2.2.3 on 2019-08-17 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='subcat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=100)),
                ('cdes', models.CharField(max_length=100)),
                ('cprice', models.TextField(max_length=100)),
                ('disc', models.TextField(max_length=100)),
                ('dprice', models.TextField(max_length=100)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.product')),
            ],
            options={
                'db_table': 'subcat',
            },
        ),
    ]
