# Generated by Django 2.2.3 on 2019-08-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_subcat'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcat',
            name='cimage',
            field=models.ImageField(default='static/images/default.JPG', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='subcat',
            name='cprice',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subcat',
            name='disc',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subcat',
            name='dprice',
            field=models.CharField(max_length=100),
        ),
    ]
