# Generated by Django 2.2.3 on 2019-09-09 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190909_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcat',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.product'),
        ),
    ]
