# Generated by Django 2.2.3 on 2019-09-26 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='SL_no',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='price',
            new_name='user_cart',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='quty',
        ),
    ]
